# Generated by Django 5.0.1 on 2024-03-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='media/default_article.svg', null=True, upload_to='article_img'),
        ),
    ]
