# Generated by Django 5.0.1 on 2024-03-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('a', 'Article'), ('p', 'Page')], default='a', max_length=1),
        ),
    ]
